{#.:.}
    <div class="row">
        <div class="col-xs-1" style="border-right: 1px solid #428BCA; padding-left: 20px;">
            <img class="img-responsive" src="upload/{avPath}">

            <span class="postMetaText"><a href="#">{username}</a></span>

            <br/>

            <span class="postMetaText">{addedAt}</span>
        </div>
        <div class="col-xs-11">
            <div class="commentText">{content}</div>
        </div>
    </div>
{/.}